"""

Revision ID: 78b953d7f5a3
Revises: 
Create Date: 2018-08-08 08:42:25.090288

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '78b953d7f5a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_model',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'COMPLETE', 'DROPPED', name='taskstatus'), nullable=True),
                    sa.Column('created_at', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('status', sa.Enum('PENDING', 'COMPLETE', 'DROPPED', name='taskstatus'), nullable=True),
                    sa.Column('created_at', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('test_data',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subject', sa.String(length=255), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('label', sa.Integer(), nullable=False),
                    sa.Column('lang', sa.String(length=100), nullable=True),
                    sa.Column('created_at', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('training_data',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subject', sa.String(length=255), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('label', sa.Integer(), nullable=False),
                    sa.Column('lang', sa.String(length=100), nullable=True),
                    sa.Column('created_at', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_data')
    op.drop_table('test_data')
    op.drop_table('task')
    op.drop_table('spam_model')
    # ### end Alembic commands ###
